server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:/Users/user/hxworkspace/h2/database
    username: root
    password: chenhuarong
    driver-class-name: org.h2.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    hikari:
#      auto-commit: true
#      minimum-idle: 2
#      idle-timeout: 60000
#      connection-timeout: 30000
#      max-lifetime: 1800000
#      pool-name: DatebookHikariCP
#      maximum-pool-size: 5

